//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_ATypePcb
    {
        public int Id { get; set; }
        public string TypePcb { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SetupDate { get; set; }
    }
}
