//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_EastechFCTCheck
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string FMachine { get; set; }
        public string FModel { get; set; }
        public string FSerial { get; set; }
        public string FNA { get; set; }
        public string FStatus { get; set; }
        public string FRemark { get; set; }
        public Nullable<System.DateTime> FReadDate { get; set; }
    }
}
