//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Eastech_Markit
    {
        public long ID { get; set; }
        public string Model { get; set; }
        public string ModelCode { get; set; }
        public string Markit { get; set; }
        public string MarkitCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
