//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_EastechFCTMarkit
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> FCTDate { get; set; }
        public string FSerial { get; set; }
        public string FMarkit { get; set; }
        public string FRemark { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
