//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_EastechEBChecker
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string State1 { get; set; }
        public string State2 { get; set; }
        public string Searial { get; set; }
        public string ZipCode { get; set; }
        public string Status01 { get; set; }
        public string Status02 { get; set; }
        public string Status03 { get; set; }
        public string Status04 { get; set; }
        public string Status05 { get; set; }
        public string Status06 { get; set; }
        public string Status07 { get; set; }
        public string Status08 { get; set; }
        public string Status09 { get; set; }
        public string Status10 { get; set; }
        public string UserName { get; set; }
    }
}
