//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_OperatorProcessData
    {
        public long Id { get; set; }
        public string Model { get; set; }
        public string Market { get; set; }
        public string TypePcb { get; set; }
        public string Process { get; set; }
        public string QrCode { get; set; }
        public string Checkert { get; set; }
        public Nullable<System.DateTime> DateT { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Wireless { get; set; }
        public string LineName { get; set; }
    }
}
