//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssySamsungErrorCode
    {
        public long ID { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorDesc { get; set; }
        public string Remark { get; set; }
    }
}
