//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box_ReturnManage
    {
        public long Id { get; set; }
        public string ReturnSerial { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string ReturnBy { get; set; }
    }
}
