//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box_IssueManage
    {
        public long Id { get; set; }
        public string IssueSerial { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string IssueBy { get; set; }
        public double IssueWight { get; set; }
        public bool IssueStatus { get; set; }
        public string Line { get; set; }
        public string Model { get; set; }
        public string Market { get; set; }
        public string PCBType { get; set; }
    }
}
