//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EASTECH_SMT_OUTPUT
    {
        public long Id { get; set; }
        public string QRCode { get; set; }
        public string programkey { get; set; }
        public string Feeder { get; set; }
        public string LineName { get; set; }
        public string Partcode { get; set; }
        public string NDesc { get; set; }
        public string DateCode { get; set; }
        public Nullable<int> usage { get; set; }
        public Nullable<System.DateTime> DateT { get; set; }
        public string Model { get; set; }
        public string Remark { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Remark4 { get; set; }
        public string Remark5 { get; set; }
    }
}
