//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EASTECH_ERROR_LOG_APPROVE
    {
        public long ID { get; set; }
        public string StaffID { get; set; }
        public string Dept { get; set; }
        public string LineName { get; set; }
        public string ErrorDetail { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Aprroved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Remark { get; set; }
        public string QRCode { get; set; }
    }
}
