//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EASTECH_PROGRAMHISTORY
    {
        public long Id { get; set; }
        public string programpartlist { get; set; }
        public string pkey { get; set; }
        public string psubkey { get; set; }
        public string fdrno { get; set; }
        public string partscode { get; set; }
        public string ndesc { get; set; }
        public Nullable<int> usage { get; set; }
        public string checkedby { get; set; }
        public string checkedtime { get; set; }
        public int reqqty { get; set; }
        public string datecode { get; set; }
        public int Solanthaylinhkien { get; set; }
        public int SoPCBCothedung { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public Nullable<int> counts { get; set; }
    }
}
