//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_BuyDeviceMonitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IT_BuyDeviceMonitor()
        {
            this.IT_DevicesManagement = new HashSet<IT_DevicesManagement>();
        }
    
        public long ID { get; set; }
        public string DBNumber { get; set; }
        public string SubDbNumber { get; set; }
        public string Model { get; set; }
        public string DDescription { get; set; }
        public int Qty { get; set; }
        public int IssueQty { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<double> ByPrice { get; set; }
        public System.DateTime ReceiverDate { get; set; }
        public string Supplier { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_DevicesManagement> IT_DevicesManagement { get; set; }
    }
}
