//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class IT_DevicesManagement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IT_DevicesManagement()
        {
            this.IT_DevicesTransaction = new HashSet<IT_DevicesTransaction>();
        }
    
        public long ID { get; set; }
        public string MaTB { get; set; }
        public string TenTB { get; set; }
        public string Model { get; set; }
        public string MotaTB { get; set; }
        public string Dept { get; set; }
        public string Loc { get; set; }
        public string Status { get; set; }
        public System.DateTime BuyDate { get; set; }
        public string ServiceTag { get; set; }
        public string ServiceCode { get; set; }
        public string MacAddress { get; set; }
        public string LoaiTB { get; set; }
        public string Supplier { get; set; }
        public bool Stock { get; set; }
        public string Remark { get; set; }
        public string NoteDBNumber { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual IT_BuyDeviceMonitor IT_BuyDeviceMonitor { get; set; }
        public virtual IT_DevicesType IT_DevicesType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_DevicesTransaction> IT_DevicesTransaction { get; set; }
    }
}
