//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JIG_CALHISTORY
    {
        public long ID { get; set; }
        public string ControlNo { get; set; }
        public System.DateTime CalDate { get; set; }
        public string Reason { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual JIG_CALDEVICES JIG_CALDEVICES { get; set; }
    }
}
