//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JIG_CALDEVICES_NEW
    {
        public long Id { get; set; }
        public string ControlNo { get; set; }
        public string EqName { get; set; }
        public string CalType { get; set; }
        public string SerialNumber { get; set; }
        public string Model { get; set; }
        public string Maker { get; set; }
        public System.DateTime CalDate { get; set; }
        public string JigSecCode { get; set; }
        public string LocName { get; set; }
        public string SStatus { get; set; }
        public string NGDetail { get; set; }
        public string DevicesDesc { get; set; }
        public string Remark { get; set; }
        public string UseStatus { get; set; }
        public System.DateTime PurDate { get; set; }
        public string ImportCond { get; set; }
        public string Origin { get; set; }
        public string OldControlNo { get; set; }
        public string FACode1 { get; set; }
        public string FACode2 { get; set; }
        public bool Real { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string BookValue { get; set; }
        public string InvoiceNo { get; set; }
    }
}
