//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JIG_SECTION
    {
        public long Id { get; set; }
        public long DeptID { get; set; }
        public string JigSecCode { get; set; }
        public string JigSecDesc { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsDisable { get; set; }
    
        public virtual UV_DEPT UV_DEPT { get; set; }
    }
}
