//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JIGH_CALDEVICES
    {
        public long Id { get; set; }
        public string ControlNo { get; set; }
        public string EqName { get; set; }
        public string Model { get; set; }
        public string Maker { get; set; }
        public Nullable<System.DateTime> MakeDate { get; set; }
        public Nullable<System.DateTime> RepairDate { get; set; }
        public string JigSecCode { get; set; }
        public string LocName { get; set; }
        public string FixLocation { get; set; }
        public string SStatus { get; set; }
        public string NGDetail { get; set; }
        public Nullable<System.DateTime> PurDate { get; set; }
        public string ImportCond { get; set; }
        public string Remark { get; set; }
        public bool Real { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CurSection { get; set; }
        public string CurLocation { get; set; }
    }
}
