//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JIGH_INOUT
    {
        public long Id { get; set; }
        public string InOut_Type { get; set; }
        public string ControlNo { get; set; }
        public string FromSecCode { get; set; }
        public string FromLocCode { get; set; }
        public string ToSecCode { get; set; }
        public string ToLocCode { get; set; }
        public string PIC { get; set; }
        public string Appr { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
