//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTSOURCE_UV_BOM
    {
        public long ID { get; set; }
        public string LotNo { get; set; }
        public string Model { get; set; }
        public string Parts { get; set; }
        public string ETPart { get; set; }
    }
}
