//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTSOURCE_ET_BOM
    {
        public long ID { get; set; }
        public string Plant { get; set; }
        public string OrderNo { get; set; }
        public string Parts { get; set; }
        public double Qty { get; set; }
    }
}
