//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    
    public partial class OutSource_UVBOM_ETBOM_Result2
    {
        public string LotNo { get; set; }
        public string OrderNo { get; set; }
        public string UVParts { get; set; }
        public string UVETParts { get; set; }
        public string ETBOMDelete { get; set; }
        public string UVParts2 { get; set; }
        public string ETParts { get; set; }
        public string ETBOMAdd { get; set; }
        public Nullable<double> Qty { get; set; }
    }
}
