//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTSOURCE_UVPartsVsETParts
    {
        public string Type { get; set; }
        public string Name { get; set; }
        public string Revision { get; set; }
        public string Title { get; set; }
        public string ETParts { get; set; }
        public string Spect { get; set; }
        public string Status { get; set; }
        public string WFProcess { get; set; }
        public string Ref { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
