//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    
    public partial class OutSource_ExportUVLotToDownload_Result1
    {
        public string ORDER_NO { get; set; }
        public string NOTE_TEXT { get; set; }
        public string RELEASE_NO { get; set; }
        public string SEQUENCE_NO { get; set; }
        public string CONTRACT { get; set; }
        public string SCHED_DIRECTION_DB { get; set; }
        public string OrderNo { get; set; }
    }
}
