//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PcbType
    {
        public int ID { get; set; }
        public string PcbType1 { get; set; }
        public string IsUV { get; set; }
        public string isKey { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    }
}
