//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMHISTORY
    {
        public string programpartlist { get; set; }
        public string fdrno { get; set; }
        public string partscode { get; set; }
        public string ndesc { get; set; }
        public Nullable<int> usage { get; set; }
        public string checkedby { get; set; }
        public string checkedtime { get; set; }
        public string rp { get; set; }
        public string rep1 { get; set; }
        public string rep2 { get; set; }
        public string rep3 { get; set; }
        public string rep4 { get; set; }
        public string rep5 { get; set; }
        public int reqqty { get; set; }
        public string datecode { get; set; }
        public string changedby { get; set; }
        public string changedtime { get; set; }
        public long Id { get; set; }
    }
}
