//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMT_OUTPUT_MIS_MATERIAL
    {
        public int ID { get; set; }
        public string OrderNo { get; set; }
        public string Partcode { get; set; }
        public double OrderQty { get; set; }
        public int LotSize { get; set; }
        public double MaterialPerPcb { get; set; }
        public double NeedQty { get; set; }
        public double Stock { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
