//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMT_OUTSOURCE_OUTHISTORY
    {
        public long ID { get; set; }
        public string OrderNo { get; set; }
        public long OuputQty { get; set; }
        public double MaterialPerPcb { get; set; }
        public string Partcode { get; set; }
        public double QtyOfPartcode { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
