//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMT_OUTSOURCE_IN_QTY
    {
        public long ID { get; set; }
        public string PartCode { get; set; }
        public System.DateTime DateCode { get; set; }
        public double Qty { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
