//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Users
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public string FullName { get; set; }
        public string ePassword { get; set; }
        public Nullable<long> DeptID { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual UV_DEPT UV_DEPT { get; set; }
    }
}
