//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EastechPCBCode
    {
        public int Id { get; set; }
        public string PcbKey { get; set; }
        public string Model { get; set; }
        public string PCBCode { get; set; }
        public string PcbType { get; set; }
        public string Statuc { get; set; }
        public Nullable<System.DateTime> DateT { get; set; }
    }
}
