//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EstechSerialGeneral
    {
        public long Id { get; set; }
        public string Serial_Number { get; set; }
        public string Model { get; set; }
        public string ModelCode { get; set; }
        public string PCBCode { get; set; }
        public string TypeOfProduct { get; set; }
        public string EndOfYear { get; set; }
        public string WeeksInYear { get; set; }
        public string DaysOfWeek { get; set; }
        public Nullable<int> SerialOfProduct { get; set; }
        public System.DateTime DateT { get; set; }
    }
}
