//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SessionLogin
    {
        public string UserId { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Dept { get; set; }
        public string HostName { get; set; }
        public string IpAddress { get; set; }
    }
}
