//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sys_Division
    {
        public int Id { get; set; }
        public string DivCode { get; set; }
        public string DivDesc { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
