//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_DEPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UV_DEPT()
        {
            this.SYS_Users = new HashSet<SYS_Users>();
            this.UV_PRO_LINE = new HashSet<UV_PRO_LINE>();
            this.JIG_SECTION = new HashSet<JIG_SECTION>();
        }
    
        public long DeptID { get; set; }
        public string DeptCode { get; set; }
        public string DeptDesc { get; set; }
        public long DivID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Users> SYS_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UV_PRO_LINE> UV_PRO_LINE { get; set; }
        public virtual UV_DIV UV_DIV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JIG_SECTION> JIG_SECTION { get; set; }
    }
}
