//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_DELETEBARCODE
    {
        public long Id { get; set; }
        public string DeleteBar { get; set; }
        public string Reason { get; set; }
        public string Lot { get; set; }
        public Nullable<long> ProcessID { get; set; }
        public string ProcessName { get; set; }
        public string LineName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
