//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_LINEREPAIRHISTORY
    {
        public long ID { get; set; }
        public string Model { get; set; }
        public string Lot { get; set; }
        public string QRCode00 { get; set; }
        public string QRCode01 { get; set; }
        public string QRCode02 { get; set; }
        public string QRCode03 { get; set; }
        public string QRCode04 { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorPosition { get; set; }
        public string CauseCode { get; set; }
        public string CauseDept { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ErrorVNDesc { get; set; }
        public string ErrorENDesc { get; set; }
    }
}
