//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_LINEPROCESS_HISTORY
    {
        public long ID { get; set; }
        public string Lot { get; set; }
        public long ProcessId { get; set; }
        public string ProcessName { get; set; }
        public string LineName { get; set; }
        public string OperatorID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string QrCode00 { get; set; }
        public string QrCode01 { get; set; }
        public string QrCode02 { get; set; }
        public string QrCode03 { get; set; }
        public string QrCode04 { get; set; }
        public string QrCode05 { get; set; }
        public string QrCode06 { get; set; }
        public string QrCode07 { get; set; }
        public string QrCode08 { get; set; }
        public string QrCode09 { get; set; }
        public string QrCode10 { get; set; }
        public string Combine01 { get; set; }
        public string Combine02 { get; set; }
        public string Combine03 { get; set; }
        public string Combine04 { get; set; }
        public string Combine05 { get; set; }
        public string EqControl01 { get; set; }
        public string EqControlName01 { get; set; }
        public Nullable<System.DateTime> EqCalDate01 { get; set; }
        public string EqControl02 { get; set; }
        public string EqControlName02 { get; set; }
        public Nullable<System.DateTime> EqCalDate02 { get; set; }
        public string EqControl03 { get; set; }
        public string EqControlName03 { get; set; }
        public Nullable<System.DateTime> EqCalDate03 { get; set; }
        public string EqControl04 { get; set; }
        public string EqControlName04 { get; set; }
        public Nullable<System.DateTime> EqCalDate04 { get; set; }
        public string EqControl05 { get; set; }
        public string EqControlName05 { get; set; }
        public Nullable<System.DateTime> EqCalDate05 { get; set; }
        public string EqControl06 { get; set; }
        public string EqControlName06 { get; set; }
        public Nullable<System.DateTime> EqCalDate06 { get; set; }
        public string EqControl07 { get; set; }
        public string EqControlName07 { get; set; }
        public Nullable<System.DateTime> EqCalDate07 { get; set; }
        public string EqControl08 { get; set; }
        public string EqControlName08 { get; set; }
        public Nullable<System.DateTime> EqCalDate08 { get; set; }
        public string EqControl09 { get; set; }
        public string EqControlName09 { get; set; }
        public Nullable<System.DateTime> EqCalDate09 { get; set; }
        public string EqControl10 { get; set; }
        public string EqControlName10 { get; set; }
        public Nullable<System.DateTime> EqCalDate10 { get; set; }
        public string JigControl01 { get; set; }
        public string JigName01 { get; set; }
        public Nullable<System.DateTime> JigCreate01 { get; set; }
        public string JigControl02 { get; set; }
        public string JigName02 { get; set; }
        public Nullable<System.DateTime> JigCreate02 { get; set; }
        public string JigControl03 { get; set; }
        public string JigName03 { get; set; }
        public Nullable<System.DateTime> JigCreate03 { get; set; }
        public string JigControl04 { get; set; }
        public string JigName04 { get; set; }
        public Nullable<System.DateTime> JigCreate04 { get; set; }
        public string JigControl05 { get; set; }
        public string JigName05 { get; set; }
        public Nullable<System.DateTime> JigCreate05 { get; set; }
        public string JigControl06 { get; set; }
        public string JigName06 { get; set; }
        public Nullable<System.DateTime> JigCreate06 { get; set; }
        public string JigControl07 { get; set; }
        public string JigName07 { get; set; }
        public Nullable<System.DateTime> JigCreate07 { get; set; }
        public string JigControl08 { get; set; }
        public string JigName08 { get; set; }
        public Nullable<System.DateTime> JigCreate08 { get; set; }
        public string JigControl09 { get; set; }
        public string JigName09 { get; set; }
        public Nullable<System.DateTime> JigCreate09 { get; set; }
        public string JigControl10 { get; set; }
        public string JigName10 { get; set; }
        public Nullable<System.DateTime> JigCreate10 { get; set; }
        public string OSG01 { get; set; }
        public string OSG02 { get; set; }
        public string OSG03 { get; set; }
        public string OSG04 { get; set; }
        public string OSG05 { get; set; }
        public string OSG06 { get; set; }
        public string OSG07 { get; set; }
        public string OSG08 { get; set; }
        public string OSG09 { get; set; }
        public string OSG10 { get; set; }
        public string Material01 { get; set; }
        public string Material02 { get; set; }
        public string Material03 { get; set; }
        public string Material04 { get; set; }
        public string Material05 { get; set; }
        public string Material06 { get; set; }
        public string Material07 { get; set; }
        public string Material08 { get; set; }
        public string Material09 { get; set; }
        public string Material10 { get; set; }
        public string Other01 { get; set; }
        public string Other02 { get; set; }
        public string Other03 { get; set; }
        public string Other04 { get; set; }
        public string Other05 { get; set; }
        public string Other06 { get; set; }
        public string Other07 { get; set; }
        public string Other08 { get; set; }
        public string Other09 { get; set; }
        public string Other10 { get; set; }
        public string GroupProcess { get; set; }
    }
}
