//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_MODELLOTINFO
    {
        public long ID { get; set; }
        public string Model { get; set; }
        public string BModel { get; set; }
        public string Lot { get; set; }
        public int LotSize { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string ProgramKey { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
    }
}
