//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_QRCODEMANAGEMENT
    {
        public long ID { get; set; }
        public string QRCODE { get; set; }
        public string FACTORY { get; set; }
        public string MODEL { get; set; }
        public string PCBCODE { get; set; }
        public string PCBTYPE { get; set; }
        public string ENDOFYEAR { get; set; }
        public string WEEKIN { get; set; }
        public string DAYINWEEK { get; set; }
        public string SEQNUMBER { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
    }
}
