//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_QRCODELINKVSLINECODE
    {
        public long ID { get; set; }
        public string Lot { get; set; }
        public string LineName { get; set; }
        public string QRCode { get; set; }
        public string QRCode01 { get; set; }
        public string QRCode02 { get; set; }
        public string QRCode03 { get; set; }
        public string QRCode04 { get; set; }
        public string QRCode05 { get; set; }
        public string NewBarCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string EmployeeID { get; set; }
    }
}
