//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_STAGING_INPUT
    {
        public long ID { get; set; }
        public string Barcode { get; set; }
        public string Location { get; set; }
        public string SmtLine { get; set; }
        public string Lot { get; set; }
        public string Model { get; set; }
        public string PeNo { get; set; }
        public string Program { get; set; }
        public string PcbName { get; set; }
        public int HsQty { get; set; }
        public int InputQty { get; set; }
        public string KeyInPerson { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
