//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_STAGING_OUTPUT
    {
        public long ID { get; set; }
        public string Barcode { get; set; }
        public int QtySMT { get; set; }
        public int QtySCL { get; set; }
        public string ToLine { get; set; }
        public string ChangeTargetLot { get; set; }
        public string Remark { get; set; }
        public string KeyInPerson { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
