//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_SMT_STD_OP_HISTORY
    {
        public long Id { get; set; }
        public string programpartlist { get; set; }
        public string fdrno { get; set; }
        public string partscode { get; set; }
        public string ndesc { get; set; }
        public Nullable<int> usage { get; set; }
        public string changedby { get; set; }
        public Nullable<System.DateTime> changedtime { get; set; }
        public Nullable<int> qty { get; set; }
        public string datecode { get; set; }
        public string linename { get; set; }
        public string statusCheck { get; set; }
        public string ipqcCheckedBy { get; set; }
        public Nullable<System.DateTime> ipqcCheckedDate { get; set; }
        public Nullable<int> ipqcCheckedQty { get; set; }
        public string ipqcCheckedDesc { get; set; }
        public string ipqcCheckedDateCode { get; set; }
        public string ipqcCheckedStatus { get; set; }
        public string resultFinal { get; set; }
        public string partscode2 { get; set; }
        public string ipqcCheckPartcode { get; set; }
        public string IDMaterial { get; set; }
        public string IDMaterial2 { get; set; }
    }
}
