//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UV_STAGING_PCBLIST
    {
        public long ID { get; set; }
        public string Lot { get; set; }
        public string Model { get; set; }
        public string BModel { get; set; }
        public string Assy { get; set; }
        public string Parts { get; set; }
        public string Desciption { get; set; }
        public string Spec { get; set; }
        public Nullable<int> HsQty { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
