//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UVASSY_CBSETTING
    {
        public long ID { get; set; }
        public string LOT { get; set; }
        public string MODEL { get; set; }
        public int DBOX_CARTON { get; set; }
        public int UNIT_DBOX { get; set; }
        public string CHECK_TYPE { get; set; }
        public string DBOX_SERIAL { get; set; }
        public string MODEL_SERIAL { get; set; }
        public int LOTSIZE { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string TEMP1 { get; set; }
        public string TEMP2 { get; set; }
        public string TEMP3 { get; set; }
        public string TEMP4 { get; set; }
        public string TEMP5 { get; set; }
    }
}
