//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UVASSY_EASTECHHISTORY
    {
        public long Id { get; set; }
        public string Serial_Number { get; set; }
        public string Model { get; set; }
        public string Lot { get; set; }
        public string Type_Base { get; set; }
        public string RepairCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
