//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UVASSY_QRCODELABEL
    {
        public long id { get; set; }
        public string Supplier { get; set; }
        public string SupplierAdd { get; set; }
        public string Market { get; set; }
        public string PN { get; set; }
        public string LN { get; set; }
        public string PD { get; set; }
        public string ED { get; set; }
        public Nullable<int> QT { get; set; }
        public string BoxNo { get; set; }
        public string UT { get; set; }
        public string SC { get; set; }
        public byte[] Images { get; set; }
    }
}
