//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UVASSY_EASTECHSERIALGENERAL
    {
        public long Id { get; set; }
        public string Serial_Number { get; set; }
        public string Model { get; set; }
        public string CCode { get; set; }
        public string PCBType { get; set; }
        public string PCBCode { get; set; }
        public string FCode { get; set; }
        public string YCode { get; set; }
        public string MCode { get; set; }
        public string DCode { get; set; }
        public Nullable<int> NCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
