//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UVASSY_LOTCONTROL
    {
        public long LotID { get; set; }
        public string Lot { get; set; }
        public string Start_Number { get; set; }
        public string End_Number { get; set; }
        public string Dbox_Barcode { get; set; }
        public string Carton_Barcode { get; set; }
        public string Model { get; set; }
        public int Lotsize { get; set; }
        public int UnitCtn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
