//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UVASSY_CBSAVEDATA
    {
        public long id { get; set; }
        public string Line { get; set; }
        public string Lot { get; set; }
        public string Model { get; set; }
        public int Unit_Carton { get; set; }
        public string Model_Serial { get; set; }
        public int Carton { get; set; }
        public string PackingID { get; set; }
        public string Dbox_Serial { get; set; }
        public string Unit_Serial { get; set; }
        public System.DateTime Date_Time { get; set; }
        public string Remark { get; set; }
        public string Keys { get; set; }
        public string Keys2 { get; set; }
        public string BatchNo { get; set; }
        public string ChangeBatchTo { get; set; }
        public string ErrorDetail { get; set; }
        public string ErrorStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
