//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UVASSY_COM2
    {
        public long id { get; set; }
        public string Lot { get; set; }
        public string Line { get; set; }
        public int Ctn_No { get; set; }
        public string Dbox_No { get; set; }
        public int Per_Ctn { get; set; }
        public string Option2 { get; set; }
        public string Dbox_Barcode { get; set; }
        public string Ctn_Code { get; set; }
        public string BatchNo { get; set; }
        public string ChangeBatchTo { get; set; }
        public string ErrorDetail { get; set; }
        public string ErrorStatus { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
