//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class UvDepartment
    {
        public long ID { get; set; }
        public string Dept { get; set; }
        public string DeptDes { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public string DivId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
