//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHS_INPUT_IQC_RETURN
    {
        public long AutoID { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> NGAYTHUHOI { get; set; }
        public string SUPPILER { get; set; }
        public Nullable<int> QTY { get; set; }
        public string LYDOTHUHOI { get; set; }
        public string NGUOITHUHOI { get; set; }
        public string PARTCODE { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
