//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHS_TRANSFER_LOTTAG
    {
        public long AutoID { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> Whs_Lottag_Iqc_Date { get; set; }
        public string Whs_Position { get; set; }
        public string Whs_CreatedBy { get; set; }
        public Nullable<System.DateTime> Whs_CreatedDate { get; set; }
        public Nullable<System.DateTime> Whs_UpdateDate { get; set; }
        public string Iqc_Lottag_Status { get; set; }
        public Nullable<System.DateTime> Iqc_Lottag_Date { get; set; }
        public string Iqc_CreatedBy { get; set; }
        public Nullable<System.DateTime> Iqc_CreatedDate { get; set; }
        public Nullable<System.DateTime> Iqc_UpdateDate { get; set; }
        public string Iqc_Check_Status { get; set; }
        public Nullable<System.DateTime> Iqc_Check_Date { get; set; }
        public string Iqc_Check_Checker { get; set; }
        public string Iqc_Check_CreatedBy { get; set; }
        public Nullable<System.DateTime> Iqc_Check_CreatedDate { get; set; }
        public Nullable<System.DateTime> Iqc_Check_UpdatedDate { get; set; }
        public string Whs_In_By { get; set; }
        public Nullable<System.DateTime> Whs_In_Date { get; set; }
        public string Whs_In_CreatedBy { get; set; }
        public Nullable<System.DateTime> Whs_In_CreatedDate { get; set; }
        public Nullable<System.DateTime> Whs_In_UpdatedDate { get; set; }
    }
}
