//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHS_PO_ERROR_KEYIN
    {
        public long AutoID { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public string PARTSCODE { get; set; }
        public string SANKYU_INVOIE { get; set; }
        public string INVOICE_NO { get; set; }
        public string PO_NO { get; set; }
        public Nullable<long> INVOICE_QTY { get; set; }
        public Nullable<long> KEYIN_QTY { get; set; }
        public Nullable<long> NO_KEYIN_QTY { get; set; }
        public string RESOLVED { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> FINISHED_DATE { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
