//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHS_RECEIVING_INPUT
    {
        public long AutoID { get; set; }
        public string ID { get; set; }
        public string SK_INVOICE { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public string SUPPLIER_INVOICE { get; set; }
        public string SUPPLIER { get; set; }
        public string SUPPLIER_CODE { get; set; }
        public string SUPPLIER_GROUP { get; set; }
        public string PARTS_CODE { get; set; }
        public string PARTS_DESC { get; set; }
        public string PARTS_SPEC { get; set; }
        public string PURCHASE_ORDER { get; set; }
        public Nullable<long> QTY { get; set; }
        public string VLOCATION { get; set; }
        public string IQC_STATUS { get; set; }
        public Nullable<long> ONHAND { get; set; }
        public Nullable<System.DateTime> USE_DATE { get; set; }
        public string LOT_NO { get; set; }
        public string REMARK { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
