//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnidenDTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHS_MONITOR_FEDEX_DHL_OTHER
    {
        public long AutoID { get; set; }
        public string ID { get; set; }
        public string FWR_TYPE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string SK_INVOICE { get; set; }
        public string INVOICE_NAME { get; set; }
        public string SUPPLIER_NAME { get; set; }
        public Nullable<int> CTN { get; set; }
        public string REMARK { get; set; }
        public string REMARK2 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
